"""
Core module for test-python-improved
Generated by Spinbox on Tue Jul 15 00:12:40 CEST 2025
"""

def hello_world():
    """Return a greeting message."""
    return "Hello from test-python-improved!"

def main():
    """Main function for the package."""
    print(hello_world())
    return True

if __name__ == "__main__":
    main()
