"""
Main entry point for test-python-improved
Generated by Spinbox on Tue Jul 15 00:12:40 CEST 2025
"""

from src.core import main as core_main

def main():
    """Main function."""
    print("Welcome to test-python-improved!")
    print("Your minimal Python environment is ready!")
    core_main()

if __name__ == "__main__":
    main()
