"""
Main entry point for test-deps-project2
Generated by Spinbox on Fri Jul 18 11:32:32 CEST 2025
"""

from src.core import main as core_main

def main():
    """Main function."""
    print("Welcome to test-deps-project2!")
    print("Your minimal Python environment is ready!")
    core_main()

if __name__ == "__main__":
    main()
