"""
Core module for test-fastapi-examples
Generated by Spinbox on Thu Jul 17 21:42:51 CEST 2025
"""

def hello_world():
    """Return a greeting message."""
    return "Hello from test-fastapi-examples!"

def main():
    """Main function for the package."""
    print(hello_world())
    return True

if __name__ == "__main__":
    main()
