# Node.js Component Dependencies
# This file maps components to their required Node.js packages

[nextjs]
dependencies = [
    "next@^14.0.0",
    "react@^18.0.0",
    "react-dom@^18.0.0",
    "axios@^1.6.0"
]
devDependencies = [
    "@types/node@^20.0.0",
    "@types/react@^18.0.0",
    "@types/react-dom@^18.0.0",
    "typescript@^5.0.0",
    "eslint@^8.0.0",
    "eslint-config-next@^14.0.0"
]
description = "Next.js React framework"

[express]
dependencies = [
    "express@^4.18.0",
    "cors@^2.8.5",
    "helmet@^7.0.0",
    "morgan@^1.10.0"
]
devDependencies = [
    "@types/express@^4.17.0",
    "@types/cors@^2.8.0",
    "@types/morgan@^1.9.0",
    "typescript@^5.0.0"
]
description = "Express.js web framework"

[tailwindcss]
dependencies = []
devDependencies = [
    "tailwindcss@^3.3.0",
    "autoprefixer@^10.4.0",
    "postcss@^8.4.0"
]
description = "Tailwind CSS utility framework"

[react]
dependencies = [
    "react@^18.0.0",
    "react-dom@^18.0.0"
]
devDependencies = [
    "@types/react@^18.0.0",
    "@types/react-dom@^18.0.0"
]
description = "React UI library"

[vite]
dependencies = []
devDependencies = [
    "vite@^4.0.0",
    "@vitejs/plugin-react@^4.0.0"
]
description = "Vite build tool"