# Python Component Dependencies
# This file maps components to their required Python packages

[fastapi]
packages = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "python-dotenv>=1.0.0"
]
description = "FastAPI web framework with async support"

[postgresql]
packages = [
    "sqlalchemy>=2.0.0",
    "asyncpg>=0.29.0",
    "alembic>=1.13.0",
    "psycopg2-binary>=2.9.0"
]
description = "PostgreSQL database integration"

[redis]
packages = [
    "redis>=5.0.0",
    "celery>=5.3.0"
]
description = "Redis caching and task queue"

[chroma]
packages = [
    "chromadb>=0.4.0",
    "sentence-transformers>=2.2.0"
]
description = "Chroma vector database"

[mongodb]
packages = [
    "beanie>=1.24.0",
    "motor>=3.3.0"
]
description = "MongoDB document database"

[openai]
packages = [
    "openai>=1.3.0",
    "tiktoken>=0.5.0"
]
description = "OpenAI API integration"

[anthropic]
packages = [
    "anthropic>=0.7.0"
]
description = "Anthropic Claude API integration"

[langchain]
packages = [
    "langchain>=0.0.350",
    "langchain-community>=0.0.1",
    "langchain-openai>=0.0.1"
]
description = "LangChain LLM framework"

[llamaindex]
packages = [
    "llama-index>=0.9.0",
    "llama-index-vector-stores-chroma>=0.1.0"
]
description = "LlamaIndex data framework"

[data-science]
packages = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "scikit-learn>=1.3.0",
    "jupyter>=1.0.0",
    "plotly>=5.15.0"
]
description = "Data science and machine learning stack"

[ai-llm]
packages = [
    "openai>=1.3.0",
    "anthropic>=0.7.0",
    "langchain>=0.0.350",
    "llama-index>=0.9.0",
    "tiktoken>=0.5.0",
    "transformers>=4.36.0"
]
description = "AI/LLM development stack"

[web-scraping]
packages = [
    "beautifulsoup4>=4.12.0",
    "requests>=2.31.0",
    "selenium>=4.15.0",
    "scrapy>=2.11.0",
    "lxml>=4.9.0"
]
description = "Web scraping and data extraction"

[api-development]
packages = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "httpx>=0.25.0",
    "python-multipart>=0.0.6"
]
description = "API development stack"