version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: test-multi-version-4572
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: test-multi-version-4572_network
