"""
Core module for test-multi-deps
Generated by Spinbox on Fri Jul 18 11:32:52 CEST 2025
"""

def hello_world():
    """Return a greeting message."""
    return "Hello from test-multi-deps!"

def main():
    """Main function for the package."""
    print(hello_world())
    return True

if __name__ == "__main__":
    main()
