"""
Main entry point for test-fastapi-examples
Generated by Spinbox on Thu Jul 17 21:42:51 CEST 2025
"""

from src.core import main as core_main

def main():
    """Main function."""
    print("Welcome to test-fastapi-examples!")
    print("Your minimal Python environment is ready!")
    core_main()

if __name__ == "__main__":
    main()
