[profile]
name = "api-only"
description = "FastAPI API with PostgreSQL and Redis caching"

[components]
fastapi = true
nextjs = false
postgresql = true
redis = true
mongodb = false
chroma = false

[configuration]
python_version = "3.12"
postgres_version = "15"
redis_version = "7"

[templates]
python_requirements = "api-development"