[profile]
name = "data-science"
description = "Data science environment with pandas, numpy, matplotlib, Jupyter, scikit-learn, and plotly"

[components]
fastapi = false
nextjs = false
postgresql = false
redis = false
mongodb = false
chroma = false

[configuration]
python_version = "3.12"

[templates]
python_requirements = "data-science"
