[profile]
name = "web-app"
description = "Full-stack web application with FastAPI, Next.js, and PostgreSQL"

[components]
fastapi = true
nextjs = true
postgresql = true
redis = false
mongodb = false
chroma = false

[configuration]
python_version = "3.12"
node_version = "20"
postgres_version = "15"

[templates]
python_requirements = "api-development"