"""
Core module for test-deps-project2
Generated by Spinbox on Fri Jul 18 11:32:32 CEST 2025
"""

def hello_world():
    """Return a greeting message."""
    return "Hello from test-deps-project2!"

def main():
    """Main function for the package."""
    print(hello_world())
    return True

if __name__ == "__main__":
    main()
