"""
Main entry point for test-multi-deps
Generated by Spinbox on Fri Jul 18 11:32:52 CEST 2025
"""

from src.core import main as core_main

def main():
    """Main function."""
    print("Welcome to test-multi-deps!")
    print("Your minimal Python environment is ready!")
    core_main()

if __name__ == "__main__":
    main()
